# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 75c45b0ae0a89a4697995b75fbe2f184fb18ef02f19817d47845922b90293bc6ed45432e0c8adceaea5d83f22743a3b1ad30f2f49dcab8410bcf2486b57d7803

test:
  secret_key_base: 9f404348c9a7e746aaea48b8719000ec52e6b442424e076f70a776ba23a91ba40db6a96c8688dff03a6a11ad04c7814cb895e369f94495aadbe51fa174749a40

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
